### ISSUE TITLE
Kodi v19 Support

### ISSUE THREAD

**Issue by TrapperHell** [cywteow/gogoanime#1]
Thank you dor this great tool! I assume that you already know, but I was naive enough to update Kodi to v19 (Matrix) and it completely disabled the addon.

Would you be awewome enough to get it working again please?

Thanks a whole lot!

**Comment by cywteow** [comment]
Hello, thank you for using my addon. I have already updated this to kodi 19 compatible. Hence it would not work for kodi 18 and below anymore. If anyone still want to use my app for kodi 18, they can still find the 1.x.x.zip in my repo and do the manual update method. Thanks.

**Comment by TrapperHell** [comment]
Brilliant! This works like a charm. Thank you for your good work.

As a matter of interest, was the update to make it v19-compatible in the referenced add-on versions only (beautifulsoup4, rerouting, resolveurl, and xbmc.python), or am I missing something ?

**Comment by cywteow** [comment]
What do you mean?

**Comment by TrapperHell** [comment]
I was just wondering if [this](https://github.com/cywteow/cywteow.github.io/commit/25a19a54481ee61030b86fea4d6f2eff090f5bfe#diff-03d52c080bceb27dd093255be6e5da68eba8888b73c74b0d091dc86532d986f4L28) section was the only thing in need of updating (apart from the MD5 hash) to make the addon compatible with Kodi v19 ?

**Comment by cywteow** [comment]
Oh, that's the repo. The md5 is like a hash/checksum to let the kodi knows that the repo has new version for update. As for your question "What makes the addon compatible with Kodi v19?" 

A: Previously addons for Kodi v18 and below are all python2. Kodi v19 onward are python3. So basically need to convert python2 -> python3 as it is not backward compatible.

**Comment by TrapperHell** [comment]
Excellent! Thank you so much for your time. I don't really do any development in python, but your addon piqued my interest into taking a look. As for Kodi, I'm really not savvy about it, so I wasn't quite sure what it was that it required for v19.

Thanks again for your time and here's wishing you all the best.

**Comment by Gohan0** [comment]
May 12th 2023 GoAnime is missing from both video add ons & add on re-pository as a feature to chose
