### ISSUE TITLE
GoGoAnime error on launch

### ISSUE THREAD

**Issue by Johnny5sword** [cywteow/gogoanime#13]
Hi!
It's me again from #12 . 

### Versions
- Kodi(19.0-ALPHA1 Git:20191116-136925bb7b) - last compatible ipa version I could find
- GoGoAnime Add-on(2.0.9) - installed from repo

### Issue
After clicking the GoGoAnime Add-on, it's loading for a little while and then shows a banner notification of GoGoAnime error and directs me to the Add-ons directory screen.

### Logs
<details>
<summary>ERROR LOG</summary>

```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'AttributeError'>
                                            Error Contents: module 'xbmcvfs' has no attribute 'translatePath'
                                            Traceback (most recent call last):
                                              File "/private/var/mobile/Containers/Data/Application/BF188770-BE9D-4BA9-BBE9-A8799AF0E4B1/Documents/Kodi/addons/plugin.video.gogoanime/addon.py", line 5, in <module>
                                                from resources.lib.database import InternalDatabase, ExternalDatabase
                                              File "/private/var/mobile/Containers/Data/Application/BF188770-BE9D-4BA9-BBE9-A8799AF0E4B1/Documents/Kodi/addons/plugin.video.gogoanime/resources/lib/database.py", line 8, in <module>
                                                __profile__ = xbmcvfs.translatePath(Addon().getAddonInfo('profile'))
                                            AttributeError: module 'xbmcvfs' has no attribute 'translatePath'
                                            -->End of Python script error report<--
```
</details>

- [FULL LOG](https://paste.kodi.tv/mifubaqexa.kodi)

**Comment by cywteow** [comment]
You're still running from IOS? It seems like there is a folder path issue. It's unable to retrieve the folder path from your device. Honestly, kodi is not designed to run in IOS.

**Comment by cywteow** [comment]
Try to get kodi 19.4 here

https://kodi.tv/download/ios

**Comment by Johnny5sword** [comment]
Unfortunately, 64-bit Kodi builds aren't compatible with my device (iPad 2 - 32-bit). So this is the last Kodi version([v19 from appdb.to](https://appdb.to/app/cydia/9)) I could find and install. From https://mirrors.kodi.tv/releases/darwin/ , 18.9 was the last released version listed there for [ios(32bits)](https://mirrors.kodi.tv/releases/darwin/ios/) while 19.4 is only available for [ios-arm64](https://mirrors.kodi.tv/releases/darwin/ios-arm64/).

**Comment by Johnny5sword** [comment]
I'm gonna try changing xbmc translatePath like the suggested solution over here:
https://github.com/maloep/romcollectionbrowser/issues/442
maybe that could work? might as well try it

**Comment by cywteow** [comment]
My code is already using xbmcvfs instead of xbmc from the error log.

**Comment by Johnny5sword** [comment]
Welp, there seems to be no solution. I'm just gonna close this then. Thanks for sparing me your time

**Comment by Johnny5sword** [comment]
I managed to get it working on my side:
 
I changed all `xbmcvfs.translatePath` -> `xbmc.translatePath`  in 
- plugin.video.gogoanime/resources/lib/database.py
- plugin.video.gogoanime/addon.py
- script.module.resolveurl/lib/resolveurl/lib/kody.py

It launches without error. Most sources work now and search is now fixed for me.

**Comment by cywteow** [comment]
Nice, this is for kodi 19 alpha version?

**Comment by Johnny5sword** [comment]
Yep, Kodi 19.0-ALPHA1 Git:20191116-136925bb7b
Looks like the newer xbmcvfs still wasn't available back then

**Comment by cywteow** [comment]
Yea. Hope you get an android tv or device soon XD this method isn't gonna last very long and resolveurl may be out of support soon.

**Comment by Johnny5sword** [comment]
You should have posted this at first lel:
# iToddler BTFO !!!
<img src="https://media.tenor.com/XQxOkKXFG7oAAAAC/satania-laugh.gif" alt="iToddlers BTFO" width="200" height="200">
crApple's walled garden and quick obsolescence is definitely why Android is better (I already have an Android device btw, I was just searching for a way to watch on my old iPad. Lesson learned, I'm never gonna buy an iCrap ever again )
