### ISSUE TITLE
Gogoanime addon down?

### ISSUE THREAD

**Issue by jaimsitecom** [cywteow/gogoanime#17]
Nothing working. Gives errors when i try to open. All ‘Favorite’ animes not opening up. Is it just me? Do i need to do set up something? Am on Kodi 20.2, cywteow 1.1.1 repo. 

Here is the error log:
https://www.mediafire.com/file/mmfnwulm477ba2c/kodi.txt/file

ty!

**Comment by islandtj** [comment]
Yup, not working since last night. Verified on multiple firestick devices.

**Comment by Mahava** [comment]
> Nothing working. Gives errors when i try to open. All ‘Favorite’ animes not opening up. Is it just me? Do i need to do set up something? Am on Kodi 20.2, cywteow 1.1.1 repo.
> 
> Here is the error log: https://www.mediafire.com/file/mmfnwulm477ba2c/kodi.txt/file
> 
> ty!

Did it ever work for you on 20.2?

**Comment by jaimsitecom** [comment]
> > Nothing working. Gives errors when i try to open. All ‘Favorite’ animes not opening up. Is it just me? Do i need to do set up something? Am on Kodi 20.2, cywteow 1.1.1 repo.
> > Here is the error log: https://www.mediafire.com/file/mmfnwulm477ba2c/kodi.txt/file
> > ty!
> 
> Did it ever work for you on 20.2?

Yes it was doin well until 2 days ago. Sad to see it’s offline now.

**Comment by mrgsi** [comment]
Looks like the website the add-on uses is down "https://www2.gogoanime.video" so the add-on will need to be updated using a different source like https://ww4.gogoanime2.org or https://ww6.gogoanimes.org or https://www5.gogoanimes.fi if cywteow has the time to play with it.

**Comment by Ichijoe2112** [comment]
> Looks like the website the add-on uses is down "https://www2.gogoanime.video" so the add-on will need to be updated using a different source like https://ww4.gogoanime2.org or https://ww6.gogoanimes.org or https://www5.gogoanimes.fi if cywteow has the time to play with it.

This is quite a simple little fix then, thank goodness.
All you need to do is to find your "Add-Ons" Folder (Wherever?) On nVidia Shield TV Pro its @ "Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.gogoanime"

The File you want to edit is called addon.py (It's a normal human readable script file. Note/Word-pad shouldn't give you much problems. (But, what do I know? I'm on a Mac, and have Idle already installed)

Long story short you'll want to edit Line 21

From
"domain = 'https://www2.gogoanime.video'"
to
<s>"domain = 'https://www5.gogoanimes.fi'</s>"
"domain = 'https://www.gogoanimehd.io'"

To fix it...

Yes I tried it before with the other two working examples given above. But, only the 5.gogoanime.fi seems to do anything on my Shield. (Sadly I know not why?), it's also a bit of fun to point out that these Sites aren't evenly synced. 5.gogoanime... is currently still missing S2E3 of Bleach TYBW, and IIRC ww.6gogo... only has Bleach up to Ep 901 the others were at least up to Ep 1000 skip a few then Ep 1029/30? just kinda find that bit odd...

Again these "Sites" don't give much appearance in being synched. But, the gogoanimehd.io site seems to be way more populated then anything else I've seen example being One Piece Eps 1001-10012 ... and 1029/30 for whatever reason. If anyone else can find better solutions please post them.

**Comment by islandtj** [comment]
> > Looks like the website the add-on uses is down "https://www2.gogoanime.video" so the add-on will need to be updated using a different source like https://ww4.gogoanime2.org or https://ww6.gogoanimes.org or https://www5.gogoanimes.fi if cywteow has the time to play with it.
> 
> This is quite a simple little fix then, thank goodness. All you need to do is to find your "Add-Ons" Folder (Wherever?) On nVidia Shield TV Pro its @ "Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.gogoanime"
> 
> The File you want to edit is called addon.py (It's a normal human readable script file. Note/Word-pad shouldn't give you much problems. (But, what do I know? I'm on a Mac, and have Idle already installed)
> 
> Long story short you'll want to edit Line 21
> 
> From "domain = 'https://www2.gogoanime.video'" to "domain = 'https://www5.gogoanimes.fi'"
> 
> To fix it. Yes I tried it before with the other two working examples given above. But, only the 5.gogoanime.fi seems to do anything on my Shield. As I write this, I would note, this only has returned the listings, I still need to actually play something.
> 
> Ok I just started up Bleach TYBW s2e2, and its WORKING!

@Ichijoe2112 Mahalo for the walkthrough fix!

**Comment by jaimsitecom** [comment]
Cywteow updated the Gogoanime addon. Everything works well again. Ty!

**Comment by Ichijoe2112** [comment]
Toasting in an old, but sadly not so forgotten thread. But the Address to GogoAnime has changed yet again.
I shall spare you the details (SCROLL UP!), but the new "current" Adress is: https://anitaku.to
Make the changes to your addon.py script, (as above.), and enjoy.
