### ISSUE TITLE
Vidstreaming and Gogo server not working?

### ISSUE THREAD

**Issue by jaimsitecom** [cywteow/gogoanime#2]
Hi. May i know if it’s a bug in the addon that makes these 2 servers not to work?  I tried to check on a pc browser if these servers work/play and they do but won’t play on kodi. 

Is there a setting i need to tweak?

Dependencies installed:
Youtube 6.8.11 matrix
Inputstream helper 0.5.4 matrix

thanks!

**Comment by cywteow** [comment]
Hello, 

Thank you for reporting that the addon is not working. I have updated GoGoAnime to v2.0.1. Try updating and let me know if it's working.

**Comment by jaimsitecom** [comment]
Been using Gogoanime 2.0.0 since Kodi Matrix rolled out. Also updated matrix to 19.1. 

Ok i will update now. Ty very much!

**Comment by jaimsitecom** [comment]
Ty so much!  This 2.0.1 update fixed it. Both servers working again. 

Thanks!!!

**Comment by jaimsitecom** [comment]
Both seem not to work again today. :( and now also STREAMHD, STREAMSB not connecting too.

**Comment by cywteow** [comment]
Fixed video links.
Seems like they are adding more encryption to protect their video links. 
Might not be able to update anymore if they add any more encryption.

**Comment by jaimsitecom** [comment]
Thanks. The usual ‘cat and mouse’ scenario. Ty a lot

**Comment by jaimsitecom** [comment]
Will this be on the next update?

**Comment by cywteow** [comment]
Did you receive v2.0.2?

**Comment by jaimsitecom** [comment]
Got it just now. Thanks so much!

**Comment by jaimsitecom** [comment]
Vidstreaming and Gogo servers are working perfectly again! Ty. Btw, is it intentional that these servers (vidstreaming and gogo) are the only ones available from now on?  

Will the other servers like Mixdrop, Streamsd, Streamshd and Doodstream be added back again?  

Thanks a lot.

**Comment by jaimsitecom** [comment]
Vidstreaming and Gogo servers are perfect again! Btw, is it intentional that these servers are the only ones available from now on?  So others like, Mixdrop and Doodstream are removed permanently as they are not shown from the options anymore? Ty

**Comment by jaimsitecom** [comment]
Oh no. Vidstreaming is not working again. Gogo the only one working. Please bring back Mixdrop, Doodstream just to make sire once Gogo hoes down anytime soon, that there will be a couple more options. 

Ty

**Comment by cywteow** [comment]
I'm not sure personally if other servers like mixdrop and doodstream working previously?

**Comment by jaimsitecom** [comment]
Mixdrop and doodstream worked before. But not as fast as gogo and vidstreaming tho. But they are options if gogo and vid go down.

**Comment by cywteow** [comment]
I just tried vidstream on a random anime and it's still working for me. Can you specify the anime title and ep here for me to test?

**Comment by jaimsitecom** [comment]
I just tried now on ONE PUNCH MAN Season 1 , you’re correct, it still works. I wonder why it gave errors a while ago with this title and others (DOROHEDORO, MOB PSYCHO). i guess it was a quick downtime only on the server side. Thanks. 

But am hoping you’d bring back Mix and Dood servers again. They’re good and decent ‘backups’ whenever Gogo and Vidstreaming go down. 

Ty very much!

**Comment by cywteow** [comment]
I've added back more servers in case GoGo or Vidstreaming is not working

**Comment by jaimsitecom** [comment]
Thanks so much!
