### ISSUE TITLE
Unable to play any content

### ISSUE THREAD

**Issue by CharlesNRU** [cywteow/gogoanime#6]
Today I tried using your add-on to stream some anime and I am unable to play any anime.
I can search, select episode but when I try to play something I would usually get a prompt to choose a server to stream from but now I simply get an error.

**Comment by cywteow** [comment]
it still works for me.

1) Did you update GoGoAnime to the latest 2.0.4?

2) Did you update ResolveUrl to latest version?
    Go System -> "Expert" Mode -> Addons -> Manage Dependancies -> ResolveUrl -> Update Version

**Comment by CharlesNRU** [comment]
Ok I couldn't find the manage dependencies in the system expert menu but I found another way to check dependencies and there was an update for resolveurl and now it works again.
Thank you!
