### ISSUE TITLE
Search function no longer working?

### ISSUE THREAD

**Issue by islandtj** [cywteow/gogoanime#9]
Recently, I've discovered that the search feature no longer works, would our developer(s) be able to resolve?  Thanks.

**Comment by Khoraxx** [comment]
Yes, such a pity that this feature no longer works. Would someone be so kind and look into it? Cheers.

**Comment by cywteow** [comment]
Fixed, Please update and try again.

**Comment by islandtj** [comment]
> Fixed, Please update and try again.

A big mahalo and thanks to @cywteow ! The search function WORKS again!  Best anime add-on!!!

**Comment by islandtj** [comment]
Thanks again, @cywteow !
